DSC_0023.JPG=Building Fire
DSC_0041.JPG=Making maps
DSC_0003.JPG=Dave Taylor Hard at work and warm!
DSC_0066.JPG=Had to move an object over the rope.
DSC_0062.JPG=Cooking Lunch as Polar Cove
DSC_0056.JPG=Using compass
DSC_0008.JPG=Dan's portable antenna
DSC_0016.JPG=Start finish line
DSC_0037.JPG=Two man saw
DSC_0011.JPG=Looking to main parking area
DSC_0006.JPG=Registration room
DSC_0013.JPG=Start finish line
DSC_0053.JPG=Mike KB8UXX hard at work Thanks Mike
DSC_0058.JPG=Mr Cork W8DHG
DSC_0082.JPG=Mike has his special bowl
DSC_0091.JPG=From the bottom Terry W8UY, Dave KB8JYV, Mike KB8UXX, Cork W8DHG, Ziggy KA8ZGE, Dan AC8NP
DSC_0063.JPG=Tiime to eat
DSC_0074.JPG=Customs check
DSC_0073.JPG=Shopping cart in its second life
DSC_0050.JPG=P & T carry
DSC_0060.JPG=First Aid
DSC_0015.JPG=keeping track of sleds
DSC_0014.JPG=first place trophy
DSC_0005.JPG=We had two different radio services
